config/routes.rb
Rails.application.routes.draw do
  # get 'user/index'
  devise_for :users
  # get 'one_transaction/index'
  # get 'one_transaction/create'
  # get 'categories/index'
  # get 'categories/show'
  # get 'categories/create'
  # get 'splash/index'

  root 'users#index'

  resources :users, only: [:index] do
    resources :categories, only: [:index, :show, :new, :create] do
      resources :entities, only: [ :index, :new, :create]
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  has_many :entitygroups
end

app/models/entitygroup.rb
class Entitygroup < ApplicationRecord
  belongs_to :entity
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :entitygroups

  def total_transaction
    entitygroups.joins(:entity, :group).sum(:amount)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :groups
  has_many :entities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(_resource)
    user_categories_path(current_user.id)
  end
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = current_user.groups

    # @entities = Entity.all
    # @entity_ids = @entity_groups.map(&:entity_id)
    # @group_entities = @entities.select { |entity| @entity_ids.include? entity.id }
    # @total = 0
    # @group_entities.each { |each| @total += each.amount }
  end

  def show; end

  def new
    @category = Group.new
    @groups = current_user.groups
  end

  def create
    uploaded_file = params[:group][:icon]

    @cat = nil
    if uploaded_file.content_type[0, 5] == 'image'
      uploaded_file.original_filename = (Time.now.to_f * 1000).to_i.to_s + uploaded_file.original_filename
      File.binwrite(Rails.root.join('app/assets', 'images', uploaded_file.original_filename), uploaded_file.read)
      @cat = Group.new(name: params[:group][:name], icon: uploaded_file.original_filename)
      @cat.user_id = current_user.id
    end

    if @cat
      if @cat.save
        redirect_to user_categories_path, notice: 'Category added successfully'
      else
        re_render :new, alert: 'Oops! Category addition failed'
      end
    else
      redirect_to user_categories_path, alert: 'Oops! Wrong file type'
    end
  end

  private

  def category_param
    # params.required(:group).permit(:name, :icon)
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def index
    @group = Group.find(params[:category_id])
    @entities = Entity.all
    @entity_groups = Group.find(params[:category_id]).entitygroups
    @entity_ids = @entity_groups.map(&:entity_id)
    @group_entities = @entities.select { |entity| @entity_ids.include? entity.id }
    @total = 0
    @group_entities.each { |each| @total += each.amount }
  end

  def new
    @transaction = Entity.new
    @current_user = current_user
  end

  def create
    @entity = Entity.new(name: params[:name], amount: params[:amount].to_i, user_id: current_user.id)
    if @entity.save
      @group = current_user.groups.select { |group| group.name == params[:group] }
      Entitygroup.create(entity_id: @entity.id, group_id: @group[0].id)
      redirect_to user_categories_path, notice: 'transaction added successfully'
    else
      render :new
    end
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/one_transaction_helper.rb
module OneTransactionHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<%= render :partial => 'partials/header', locals: { screen_name: 'Categories' } %>
<%= render :partial => 'partials/notification' %>
    
<h1 class="budgets">Budget Categories</h1>

<div class="cat-container">
  <% @categories.each do |cat|  %>
    <%= link_to user_category_entities_path(:category_id => cat.id), :class => 'cat-item' do %>
      <div class="cat">
        <%= image_tag "#{cat.icon}", :class => "avatar" %>
        
        <div class="time cong">
          <p class="cat-name"><%= cat.name %></p>
          <p class="cat-tot">Total: $<%= cat.total_transaction.to_s.gsub(/\B(?=(...)*\b)/, ',') %></p>
       
        </div>

        <div class="time">
          <p class="cat-item"><%= cat.created_at.localtime.to_s[0, 10] %></p>
          <p class="cat-item"><%= cat.created_at.localtime.to_s[11..19] %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

 <div class="btn-container">
 <button class="btn btn-primary btn-center"><%= link_to "Add a new category", new_user_category_path, :class => 'primary-inner' %></button>
 </div>

app/views/categories/new.html.erb
<%= render :partial => 'partials/header', locals: { screen_name: 'Add Category' } %>
<%= render :partial => 'partials/notification' %>
<%= link_to user_categories_path do %>
  <i class="fa fa-arrow-left" aria-hidden="true"></i>
<% end %>

<div class="signup">
  <div class='inner-box'>
  <h2>Let's add a new category</h2>

  <%= form_with model: @category, url: user_categories_path, multipart: true do |form| %>
    <div class="field">
    <%= form.label :title, "Category name" %>
    <%= form.text_field :name, placeholder: "Name", required: true, :class => 'input' %>
  </div>

  <div class="field">
  <%= form.label :title, "Add Icon" %>
  <%= form.file_field :icon, placeholder: "Add file", required: true, :class => 'input' %>
</div>

<div class="field">
  <%= form.submit "Save", class: "btn btn-primary", disable_with: "Please wait..." %>
</div>
  <% end %>
  </div>

</div>

app/views/entities/index.html.erb
<%= render :partial => 'partials/header', locals: { screen_name: 'Transaction' } %>
<%= render :partial => 'partials/notification' %>
<%= link_to user_categories_path do %>
  <i class="fa fa-arrow-left" aria-hidden="true"></i>
<% end %>
<div class="wrapper">
  <h2 class="trans-name"><%= @group.name %> Transaction</h2>

  <div class="t-wrapper">
    <div class="line">
      <h5>Item</h5>
      <h5>Budget</h5>
    </div>

    <hr >

    <% @group_entities.reverse.each do |entity|  %>
      <div class="line">
        <p><%= entity.name %></p>
        <p>$<%= entity.amount.to_s.gsub(/\B(?=(...)*\b)/, ',') %></p>
      </div>
    <% end %>
      <hr >
      <div class="line">
        <h6>Total Budget</h6>
        <h6>$<%= @total.to_s.gsub(/\B(?=(...)*\b)/, ',') %></h6>
      </div>
  </div>

  <div class="btn-container">
    <button class="btn btn-primary btn-center"><%= link_to "add a new transaction", new_user_category_entity_path, :class => 'primary-inner'  %></button>
  </div>
</div>

app/views/entities/new.html.erb
<%= render :partial => 'partials/header', locals: { screen_name: 'Add Transaction' } %>
<%= render :partial => 'partials/notification' %>
<a href="javascript:history.back()"><i class="fa fa-arrow-left" aria-hidden="true"></i></a>
  

<div class="signup">
  <div class='inner-box'>
    <h1>Let's add a transaction</h1>

    <%= form_with model: @category, url: user_category_entities_path, method: :post do |form| %>
      <div class="field">
        <%= form.label :title, "Transaction name" %>
        <%= form.text_field :name, placeholder: "Name", required: true, :class => 'input' %>
      </div>

      <div class="field">
        <%= form.label :title, "Transaction amount" %>
        <%= form.number_field :amount, placeholder: "Amount", required: true, :class => 'input' %>
      </div>
      
      <div class="field">
        <%= form.label :title, "Budget category" %>
        <%= form.select :group, @current_user.groups.map { |group| group.name}, :required => true, :class => 'input' %>
      </div>

      <div class="field">
        <%= form.submit "Save", class: "btn btn-primary", disable_with: "Please wait..." %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <main class="main">
      <%= yield %>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </body>
</html>

app/views/partials/_header.html.erb
<div>
  <h1 class="app-name">Budget App</h1>
  <div>
    <div class="pos-f-t">
      <div class="collapse" id="navbarToggleExternalContent">
        <div class="bg-dark p-4">
          <h4 class="text-white">Collapsed content</h4>
          <span class="text-muted">Toggleable via the navbar brand.</span>
        </div>
      </div>
      <nav class="navbar navbar-dark" id="nav-bar">
        <div class="empty"></div>
        <h2 class="screen-name"><%= screen_name %></h2>
        <div>
          <% if user_signed_in? %> 
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'nav-signup'  %>
          <% else %>
            <%= button_to "Sign in", new_user_session_url, :class => 'nav-signup'  %>
          <% end %>
        </div>
      </nav>
    </div>
  </div>
  </div>

app/views/partials/_notification.html.erb
<div class="notification-container">
  <span class="notice"><%= notice %></span>
  <span class="alert"><%= alert %></span>
</div>

app/views/splash/index.html.erb
<h1>Splash#index</h1>
<p>Find me in app/views/splash/index.html.erb</p>

app/views/users/index.html.erb
<%= render :partial => 'partials/header', locals: { screen_name: 'Let\'s Go!' } %>
<%= render :partial => 'partials/notification' %>

<div class="splash-container">
  <h1 class='app-intro'>Welcome!</h1>
  <p class='splash-login'><%= link_to "Sign In", new_user_session_path,  :class => "splash-login-text" %></p>
  <p class='splash-logout'><%= link_to "Sign Up", new_user_registration_path, :class => "splash-logout-text" %></p>
</div>